### ISSUE TITLE
the error of bleu

### ISSUE THREAD

**Issue by tuyunbin** [LibertFan/ImageCaption#1]
Hi, thank you for your awesome work, but when I ran Trainer.py, I met a error:
scores = self.measurer(hypos, refs, bleu=opts.bleu, metric=opts.metric)
TypeError: every_measure_score() got an unexpected keyword argument 'bleu'

I cannot find metric and bleu in opts, so how can I solve this problem?

**Comment by LibertFan** [comment]
I have fixed it. Remove these two arguments in self.measurer.

**Comment by tuyunbin** [comment]
Thank you!
